site_name: Open Data Toolkit
pages:
    - [index.md, "General Information", "Open Data Toolkit"]
    - [getting-started.md, "General Information", "Getting Started"]
    - [planning.md, "General Information", "Planning"]
    - [publishing-your-data.md, "General Information", "Publishing Your Data"]
    - [nationalmap.md, "NationalMap", "NationalMap"]
    - [data-gov-au-starting.md, "Using data.gov.au", "Starting on data.gov.au"]
    - [data-gov-au-managing-org.md "Using data.gov.au", "Managing your organisation"]
theme: readthedocs
site_favicon: imgs/favicon.ico
google_analytics:
